[package]
edition = "2018"
name = "abc225_e"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
num-rational = "0.2.4"
